package:
  name: pyqtconfig
  version: "0.8.13"

source:
# this is used for build from git hub
  git_rev: 0.8.13
  git_url: https://github.com/mjirik/pyqtconfig.git

requirements:
  build:
    - python
    - setuptools
    - pyqt
  run:
    - python
    - pyqt

test:
  imports:
    - pyqtconfig
about:
  home: https://github.com/mfitzp/pyqtconfig
  license: BSD License
  summary: 'An API for keeping PyQt widgets in sync with a config dictionary or QSettings object.',

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
