package:
  name: pyqtconfig
  version: "0.8.11"

source:
# this is used for build from git hub
  git_rev: 0.8.11
  git_url: https://github.com/mjirik/pyqtconfig.git

  # this is used for pypi
  # fn: io3d-1.0.30.tar.gz
  # url: https://pypi.python.org/packages/source/i/io3d/io3d-1.0.30.tar.gz
  # md5: a3ce512c4c97ac2410e6dcc96a801bd8
requirements:
  build:
    - python
    - setuptools
    - pyqt
#    #    - {{ pin_compatible('io3d', max_pin='x') }}
  run:
    - python
    - pyqt

test:
  imports:
    - pyqtconfig
about:
  home: https://github.com/mfitzp/pyqtconfig
  license: BSD License
  summary: 'An API for keeping PyQt widgets in sync with a config dictionary or QSettings object.',

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
